### ISSUE TITLE
Type pages 12-20

### ISSUE THREAD

**Issue by larsbrinkhoff** [sebras/JOSS-I#3]
Do my part for JOSS-I.

**Comment by larsbrinkhoff** [comment]
Sorry, this has been delayed.  But not forgotten.

**Comment by sebras** [comment]
> Sorry, this has been delayed. But not forgotten.

No worries! The listing has been waiting a few decades. :)

**Comment by larsbrinkhoff** [comment]
This is now in progress.

**Comment by sebras** [comment]
> This is now in progress.

Not only in progress, it has been finished! Thank you! :)
